/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenerateTab.java
 *
 * Created on Nov 17, 2011, 12:12:00 AM
 */
package generate_ui;

/**
 *
 * @author Andy
 */
public class GenerateTab extends javax.swing.JPanel {

    /** Creates new form GenerateTab */
    public GenerateTab() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(896, 403));
        setMinimumSize(new java.awt.Dimension(896, 403));
        setName("mainpanel"); // NOI18N

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(139, 139));
        jTabbedPane1.setName("Generate Tab"); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(200, 200));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("jLabel2");
        jTabbedPane1.addTab("<html><body leftmargin=30 topmargin=50 marginwidth=60 marginheight=50>Components</body></html>", jLabel2);

        jLabel1.setText("jLabel1");
        jTabbedPane1.addTab("<html><body leftmargin=30 topmargin=50 marginwidth=60 marginheight=50>Preferences</body></html>", jLabel1);

        jLabel3.setText("jLabel3");
        jLabel3.setMinimumSize(new java.awt.Dimension(34, 100));
        jTabbedPane1.addTab("<html><body leftmargin=30 topmargin=50 marginwidth=60 marginheight=50>Generate</body></html>", jLabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("foo\n");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
